#!/usr/bin/env node
// Pre-build the docs content into a TypeScript module so the runtime
// doesn't touch the filesystem and process.cwd() doesn't matter.
// Reads documentation/gitbook/ → writes src/lib/docs-content.ts.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..", "..", "documentation", "gitbook");
const OUT = path.resolve(__dirname, "..", "src", "lib", "docs-content.ts");

if (!fs.existsSync(ROOT)) {
  console.error(`docs source not found: ${ROOT}`);
  process.exit(1);
}

const files = {};
function walk(dir, relBase = "") {
  for (const name of fs.readdirSync(dir)) {
    if (name.startsWith(".")) continue;
    const abs = path.join(dir, name);
    const rel = relBase ? `${relBase}/${name}` : name;
    const stat = fs.statSync(abs);
    if (stat.isDirectory()) walk(abs, rel);
    else if (name.endsWith(".md")) files[rel] = fs.readFileSync(abs, "utf8");
  }
}
walk(ROOT);

const lines = [
  "// Auto-generated by frontend/scripts/build-docs.mjs — do not edit by hand.",
  "// Source: documentation/gitbook/",
  "",
  "export const DOCS: Record<string, string> = {",
];
for (const [k, v] of Object.entries(files)) {
  lines.push(`  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
}
lines.push("};");
lines.push("");

fs.writeFileSync(OUT, lines.join("\n"), "utf8");
console.log(
  `Wrote ${Object.keys(files).length} markdown files → ${path.relative(process.cwd(), OUT)}`,
);
